## Fire up GraphLab Create

In [2]:
import pandas as pd

### Load a tabular data set

In [11]:
df = pd.read_csv("./people-example.csv")
df

  First Name Last Name        Country  age
0        Bob     Smith  United States   24
1      Alice  Williams         Canada   23
2    Malcolm      Jone        England   22
3      Felix     Brown            USA   23
4       Alex    Cooper         Poland   23
5        Tod  Campbell  United States   22
6      Derek      Ward    Switzerland   25

### Canvas

In [8]:
import matplotlib.pyplot as plt

In [26]:
s = df.groupby(['age'])['age'].count()
s

age
22    2
23    3
24    1
25    1
Name: age, dtype: int64

In [28]:
plt.bar(s.index, s.values)

### Inspect columns of dataset

In [29]:
df['Country']

0    United States
1           Canada
2          England
3              USA
4           Poland
5    United States
6      Switzerland
Name: Country, dtype: object

In [30]:
df['age']

0    24
1    23
2    22
3    23
4    23
5    22
6    25
Name: age, dtype: int64

In [31]:
df['age'].mean()

23.142857142857142

In [32]:
df['age'].max()

25

### Create new columns

In [33]:
df

  First Name Last Name        Country  age
0        Bob     Smith  United States   24
1      Alice  Williams         Canada   23
2    Malcolm      Jone        England   22
3      Felix     Brown            USA   23
4       Alex    Cooper         Poland   23
5        Tod  Campbell  United States   22
6      Derek      Ward    Switzerland   25

In [36]:
df['Full Name'] = df['First Name'] + " " + df['Last Name']

In [37]:
df

  First Name Last Name        Country  age       Full Name
0        Bob     Smith  United States   24       Bob Smith
1      Alice  Williams         Canada   23  Alice Williams
2    Malcolm      Jone        England   22    Malcolm Jone
3      Felix     Brown            USA   23     Felix Brown
4       Alex    Cooper         Poland   23     Alex Cooper
5        Tod  Campbell  United States   22    Tod Campbell
6      Derek      Ward    Switzerland   25      Derek Ward

In [38]:
df['age'] + 2

0    26
1    25
2    24
3    25
4    25
5    24
6    27
Name: age, dtype: int64

### Use the apply function to do a advance transformation of data

In [40]:
def transform_country(country):
    if country == "USA":
        return "United States"
    else:
        return country

In [41]:
transform_country("Brazil")

'Brazil'

In [42]:
transform_country("USA")

'United States'

In [43]:
df['Country'].apply(transform_country)

0    United States
1           Canada
2          England
3    United States
4           Poland
5    United States
6      Switzerland
Name: Country, dtype: object